spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 30MB
  redis:
    host: 120.25.144.169
    port: 6379
logging:
  level:
    com:
      itheima:
        admin:
          mapper: debug
server:
  port: 9300

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #???????
  thumb-image:
    width: 150
    height: 150
  #TrackerList??,????
  tracker-list: 120.25.144.169:22122
  web-server-url: http://120.25.144.169:8888/
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000

url:
  fileServerUrl: http://120.25.144.169/

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: heima-mm-tast
      port: 999

