spring:
  datasource:
    url: jdbc:mysql://10.54.27.203:3306/heima_mm?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #????
  type-aliases-package: com.itheima.security_demo.pojo  #??????????
