spring:
  datasource:
    url: jdbc:mysql://120.25.144.169/heima_mm?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
  type-aliases-package: com.itheima.admin.pojo  #实体类的别名的包扫描

logging:
  level:
    com:
     itheima:
      admin:
        mapper: debug
server:
  port: 9000

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: heima-mm-question
      port: 1002



