spring:

  datasource:
    url: jdbc:mysql://120.25.144.169:3306/heima_mm?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 30MB
  redis:
    host: 120.25.144.169
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
  type-aliases-package: com.itheima.admin.pojo  #实体类的别名的包扫描

logging:
  level:
    com:
      itheima:
        admin:
          mapper: debug
server:
  port: 9001

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 120.25.144.169:22122
  web-server-url: http://120.25.144.169:8888/
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000

url:
  fileServerUrl: http://120.25.144.169/

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: heima-mm-question
      port: 1000



